---
title: "TidyTuesday: Visualizing Plastic Pollution"
description: |
  This post contains the code and output for the 2021-01-26 TidyTuesday.
author:
  - name: Kristin Gill
    url: {}
date: 02-02-2021
output:
  distill::distill_article:
    self_contained: false
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(maptools)
library(sf)
library(raster)
library(tmap)
library(here)
library(dplyr)
library(jsonlite)
library(geojsonR)
library(rgdal)
library(data.table)
library(leaflet)
library(janitor)
```

## Wrangling the Data
```{r}
# read in the data
plastics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv') %>% 
  dplyr::select(!grand_total) %>% 
  pivot_longer(cols = 5:11, names_to = "plastics", values_to = "counts") %>% 
  filter(year == 2020) %>% 
  filter(str_detect(parent_company, "Pepsi")) %>% 
  filter(parent_company == "Pepsico") %>% 
  dplyr::select(!volunteers) %>% 
  dplyr::select(!empty) %>% 
  dplyr::select(!num_events) %>%
  mutate(country = case_when(
    country == "United States of America" ~ "United States",
    country == "United Kingdom of Great Britain & Northern Ireland" ~ "United Kingdom",
    country == "Korea" ~ "South Korea",
    TRUE ~ as.character(country)
  ))

# read in the data
country_lat_long <- read_csv("world_country_and_usa_states_latitude_and_longitude_values.csv") %>% dplyr::select(country, latitude, longitude)

world_map <- read_sf("99bfd9e7-bb42-4728-87b5-07f8c8ac631c2020328-1-1vef4ev.lu5nk.shp") %>% clean_names() %>% 
  rename("country" = "cntry_name")

world_countries_map <- read_sf("World_Countries__Generalized_.shp") %>% 
  clean_names()

# merge the data
merged_data <- merge(plastics, world_countries_map, by = "country")

merge_2 <- merge(merged_data, country_lat_long, by = "country")
```

```{r, include = FALSE}
data_shapefile <- st_as_sf(merge_2, coords = c("longitude", "latitude"))

st_transform(world_countries_map, 4326)

st_crs(data_shapefile) = 4326
```

## Creating the Map
```{r}
ggplot()+
  geom_sf(data = world_countries_map, size = 0.5, color = "darkgray", fill = "antiquewhite1") +
  geom_sf(data = data_shapefile, aes(size = counts), color = "dodgerblue4") +
  theme(panel.grid.major = element_line(colour = gray(0.5), linetype = "dashed", 
         size = 0.5), panel.background = element_rect(fill = "aliceblue"), 
         panel.border = element_rect(fill = NA)) +
  labs(x = "Longitude",
       y = "Latitude",
       title = "Pepsi Plastic Found Around the World by Break Free from Plastic, 2020") +
  coord_sf(xlim = c(-180, 180), ylim = c(-90, 90), expand = FALSE)
```

