---
title: CV
name: Kristin
surname: Gill
position: "Master of Environmental Science and Management Student"
address: "Bren School of Environmental Science & Management, University of California, San Diego"
phone: +1-408-857-73833
email: "kristin_gill@ucsb.edu"
github: kristingill
linkedin: Kristin Gill
date: "`r format(Sys.time(), '%B %Y')`"
output:
  vitae::markdowncv:
  css: postcards.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

## Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

## Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Master of Environmental Science and Management", "2022", "Bren School, University of California, Santa Barbara", "Santa Barbara, CA", 
  "Bachelor of Science, Environmental Science (Ecology, Behavior, and Evolution)", "2019", "University of California, San Diego", "San Diego, CA"
  
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

## Experience

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  2019, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

## Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

